#pragma once 

#include "laminpie_conf.h"
#include "../laminpie_internal.h"

#if !LAMINPIE_ENABLE_SYSTEMS
#   error "LAMINPIE_ENABLE_SYSTEMS is not enabled, enable it in the menuconfig or lamin_conf.h"
#endif


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////// 模块日志开关配置 ///////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// 定义主模块日志开关
#if !defined(LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG)
#       define LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG  CONFIG_LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG
#   else
#       define LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

// 子模块日志开关定义
#if LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG
    // CORE.APP 子模块
    #if !defined(LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG)
    #   if defined(CONFIG_LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG)
    #       define LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG  CONFIG_LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG
    #   else
    #       define LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG  (0)
    #   endif
    #endif

    // CORE.EVENT 子模块
    #if !defined(LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG)
    #   if defined(CONFIG_LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG)
    #       define LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG  CONFIG_LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG
    #   else
    #       define LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG  (0)
    #   endif
    #endif

    // LAMINPIE 管理模块
    #if !defined(LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG)
    #   if defined(CONFIG_LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG)
    #       define LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG  CONFIG_LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG
    #   else
    #       define LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG  (0)
    #   endif
    #endif

    #if !defined(LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG)
    #   if defined(CONFIG_LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG)
    #       define LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG  CONFIG_LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG
    #   else
    #       define LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG  (0)
    #   endif
    #endif
#else
    // 当主模块日志禁用时，所有子模块日志也禁用
    #define LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG       (0)
    #define LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG     (0)
    #define LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG (0)
    #define LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG (0)
#endif

// 便捷的模块日志检查宏
#define LAMINPIE_LOG_ENABLED_SYSTEM_APP       (LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG && LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG)
#define LAMINPIE_LOG_ENABLED_SYSTEM_EVENT     (LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG && LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG)
#define LAMINPIE_LOG_ENABLED_SYSTEM_MANAGER    (LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG && LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG)
#define LAMINPIE_LOG_ENABLED_SYSTEM_CORE       (LAMINPIE_SYSTEM_ENABLE_DEBUG_LOG && LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG)

// 定义日志标签
#define LAMINPIE_SYSTEM_APP_LOG_TAG     "laminpie.app"
#define LAMINPIE_SYSTEM_EVENT_LOG_TAG   "laminpie.event"
#define LAMINPIE_SYSTEM_MANAGER_LOG_TAG "laminpie.manager"
#define LAMINPIE_SYSTEM_CORE_LOG_TAG    "laminpie.core"

#if LAMINPIE_LOG_ENABLED_SYSTEM_APP
#   define SYSTEM_APP_LOG_TRACE(fmt, ...) LP_MOD_LOG_TRACE(LAMINPIE_SYSTEM_APP_LOG_TAG, LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_APP_LOG_DEBUG(fmt, ...) LP_MOD_LOG_DEBUG(LAMINPIE_SYSTEM_APP_LOG_TAG, LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_APP_LOG_INFO(fmt, ...) LP_MOD_LOG_INFO(LAMINPIE_SYSTEM_APP_LOG_TAG, LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_APP_LOG_WARN(fmt, ...) LP_MOD_LOG_WARN(LAMINPIE_SYSTEM_APP_LOG_TAG, LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_APP_LOG_ERROR(fmt, ...) LP_MOD_LOG_ERROR(LAMINPIE_SYSTEM_APP_LOG_TAG, LAMINPIE_SYSTEM_APP_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#else
#   define SYSTEM_APP_LOG_TRACE(fmt, ...) ((void)0)
#   define SYSTEM_APP_LOG_DEBUG(fmt, ...) ((void)0)
#   define SYSTEM_APP_LOG_INFO(fmt, ...) ((void)0)
#   define SYSTEM_APP_LOG_WARN(fmt, ...) ((void)0)
#   define SYSTEM_APP_LOG_ERROR(fmt, ...) ((void)0)
#endif

#if LAMINPIE_LOG_ENABLED_SYSTEM_EVENT
#   define SYSTEM_EVENT_LOG_TRACE(fmt, ...) LP_MOD_LOG_TRACE(LAMINPIE_SYSTEM_EVENT_LOG_TAG, LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_EVENT_LOG_DEBUG(fmt, ...) LP_MOD_LOG_DEBUG(LAMINPIE_SYSTEM_EVENT_LOG_TAG, LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_EVENT_LOG_INFO(fmt, ...) LP_MOD_LOG_INFO(LAMINPIE_SYSTEM_EVENT_LOG_TAG, LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_EVENT_LOG_WARN(fmt, ...) LP_MOD_LOG_WARN(LAMINPIE_SYSTEM_EVENT_LOG_TAG, LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_EVENT_LOG_ERROR(fmt, ...) LP_MOD_LOG_ERROR(LAMINPIE_SYSTEM_EVENT_LOG_TAG, LAMINPIE_SYSTEM_EVENT_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#else
#   define SYSTEM_EVENT_LOG_TRACE(fmt, ...) ((void)0)
#   define SYSTEM_EVENT_LOG_DEBUG(fmt, ...) ((void)0)
#   define SYSTEM_EVENT_LOG_INFO(fmt, ...) ((void)0)
#   define SYSTEM_EVENT_LOG_WARN(fmt, ...) ((void)0)
#   define SYSTEM_EVENT_LOG_ERROR(fmt, ...) ((void)0)
#endif

#if LAMINPIE_LOG_ENABLED_SYSTEM_MANAGER
#   define SYSTEM_MANAGER_LOG_TRACE(fmt, ...) LP_MOD_LOG_TRACE(LAMINPIE_SYSTEM_MANAGER_LOG_TAG, LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_MANAGER_LOG_DEBUG(fmt, ...) LP_MOD_LOG_DEBUG(LAMINPIE_SYSTEM_MANAGER_LOG_TAG, LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_MANAGER_LOG_INFO(fmt, ...) LP_MOD_LOG_INFO(LAMINPIE_SYSTEM_MANAGER_LOG_TAG, LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_MANAGER_LOG_WARN(fmt, ...) LP_MOD_LOG_WARN(LAMINPIE_SYSTEM_MANAGER_LOG_TAG, LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_MANAGER_LOG_ERROR(fmt, ...) LP_MOD_LOG_ERROR(LAMINPIE_SYSTEM_MANAGER_LOG_TAG, LAMINPIE_SYSTEM_MANAGER_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#else
#   define SYSTEM_MANAGER_LOG_TRACE(fmt, ...) ((void)0)
#   define SYSTEM_MANAGER_LOG_DEBUG(fmt, ...) ((void)0)
#   define SYSTEM_MANAGER_LOG_INFO(fmt, ...) ((void)0)
#   define SYSTEM_MANAGER_LOG_WARN(fmt, ...) ((void)0)
#   define SYSTEM_MANAGER_LOG_ERROR(fmt, ...) ((void)0)
#endif

#if LAMINPIE_LOG_ENABLED_SYSTEM_CORE
#   define SYSTEM_CORE_LOG_TRACE(fmt, ...) LP_MOD_LOG_TRACE(LAMINPIE_SYSTEM_CORE_LOG_TAG, LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_CORE_LOG_DEBUG(fmt, ...) LP_MOD_LOG_DEBUG(LAMINPIE_SYSTEM_CORE_LOG_TAG, LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_CORE_LOG_INFO(fmt, ...) LP_MOD_LOG_INFO(LAMINPIE_SYSTEM_CORE_LOG_TAG, LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_CORE_LOG_WARN(fmt, ...) LP_MOD_LOG_WARN(LAMINPIE_SYSTEM_CORE_LOG_TAG, LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#   define SYSTEM_CORE_LOG_ERROR(fmt, ...) LP_MOD_LOG_ERROR(LAMINPIE_SYSTEM_CORE_LOG_TAG, LAMINPIE_SYSTEM_CORE_ENABLE_DEBUG_LOG, fmt, ##__VA_ARGS__)
#else
#   define SYSTEM_CORE_LOG_TRACE(fmt, ...) ((void)0)
#   define SYSTEM_CORE_LOG_DEBUG(fmt, ...) ((void)0)
#   define SYSTEM_CORE_LOG_INFO(fmt, ...) ((void)0)
#   define SYSTEM_CORE_LOG_WARN(fmt, ...) ((void)0)
#   define SYSTEM_CORE_LOG_ERROR(fmt, ...) ((void)0)
#endif
