#!/usr/bin/env python3
"""
Configuration Generator for LaminPie
Generates sdkconfig.h from Kconfig files and default configurations.
"""

import os
import sys
import argparse
from pathlib import Path

# Import our Kconfig parser
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from kconfig_parser import KconfigParser

class ConfigGenerator:
    def __init__(self):
        self.parser = KconfigParser()
        self.default_configs = {}
        
    def load_defaults(self, defaults_file):
        """Load default configurations from file"""
        if not os.path.exists(defaults_file):
            return False
            
        with open(defaults_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    if '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        value = value.strip()
                        
                        # Convert value based on type
                        if value.lower() in ('y', 'yes', 'true', '1'):
                            self.default_configs[key] = True
                        elif value.lower() in ('n', 'no', 'false', '0'):
                            self.default_configs[key] = False
                        elif value.isdigit():
                            self.default_configs[key] = int(value)
                        else:
                            self.default_configs[key] = value.strip('"')
        return True
    
    def generate_sdkconfig(self, output_file):
        """Generate sdkconfig.h file"""
        # Create output directory if it doesn't exist
        output_dir = os.path.dirname(output_file)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("/*\n")
            f.write(" * SDK Configuration Header for LaminPie\n")
            f.write(" * Auto-generated from Kconfig files\n")
            f.write(" * Generated by config_generator.py\n")
            f.write(" */\n\n")
            f.write("#ifndef SDKCONFIG_H\n")
            f.write("#define SDKCONFIG_H\n\n")
            
            # Platform Configuration
            f.write("// ============================================================================\n")
            f.write("// Platform Configuration\n")
            f.write("// ============================================================================\n\n")
            f.write("#define CONFIG_PLATFORM_GENERIC 1\n\n")
            
            # Core Configuration
            f.write("// ============================================================================\n")
            f.write("// LaminPie Core Configuration\n")
            f.write("// ============================================================================\n\n")
            
            # Generate config definitions
            for config_name, config_info in self.parser.configs.items():
                config_value = self.default_configs.get(config_name, config_info['default'])
                
                # Handle choice configurations
                if config_name.startswith('LAMINPIE_USE_OS_') and config_name != 'LAMINPIE_USE_OS_VALUE':
                    # This is a choice option, only define the selected one
                    if config_value:
                        f.write(f"#define CONFIG_{config_name} 1\n")
                    else:
                        f.write(f"#define CONFIG_{config_name} 0\n")
                elif config_info['type'] == 'bool':
                    if config_value:
                        f.write(f"#define CONFIG_{config_name} 1\n")
                    else:
                        f.write(f"#define CONFIG_{config_name} 0\n")
                elif config_info['type'] == 'int':
                    f.write(f"#define CONFIG_{config_name} {config_value}\n")
                elif config_info['type'] == 'string':
                    f.write(f"#define CONFIG_{config_name} \"{config_value}\"\n")
            
            # Add LAMINPIE_USE_OS_VALUE based on choice selection
            f.write("\n// OS Selection Value\n")
            os_value = 1  # Default to STD_THREAD
            if self.default_configs.get('LAMINPIE_USE_OS_STD_THREAD', True):
                os_value = 1
            elif self.default_configs.get('LAMINPIE_USE_OS_PTHREAD', False):
                os_value = 2
            elif self.default_configs.get('LAMINPIE_USE_OS_FREERTOS', False):
                os_value = 3
            elif self.default_configs.get('LAMINPIE_USE_OS_RTTHREAD', False):
                os_value = 4
            elif self.default_configs.get('LAMINPIE_USE_OS_CUSTOM', False):
                os_value = 5
            elif self.default_configs.get('LAMINPIE_USE_OS_NONE', False):
                os_value = 0
            
            f.write(f"#define CONFIG_LAMINPIE_USE_OS_VALUE {os_value}\n\n")
            
            # Additional platform-specific definitions
            f.write("// ============================================================================\n")
            f.write("// Platform-Specific Definitions\n")
            f.write("// ============================================================================\n\n")
            
            # Generic platform definitions
            f.write("#ifndef __cplusplus\n")
            f.write("#include <stdint.h>\n")
            f.write("#include <stdbool.h>\n")
            f.write("#include <stddef.h>\n")
            f.write("#endif\n\n")
            
            # Common macros
            f.write("#ifndef ARRAY_SIZE\n")
            f.write("#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))\n")
            f.write("#endif\n\n")
            
            f.write("#ifndef MIN\n")
            f.write("#define MIN(a, b) ((a) < (b) ? (a) : (b))\n")
            f.write("#endif\n\n")
            
            f.write("#ifndef MAX\n")
            f.write("#define MAX(a, b) ((a) > (b) ? (a) : (b))\n")
            f.write("#endif\n\n")
            
            # ESP-IDF compatibility macros
            f.write("// ESP-IDF compatibility macros\n")
            f.write("#ifndef ESP_LOGI\n")
            f.write("#define ESP_LOGI(tag, format, ...) printf(\"[%s] \" format \"\\n\", tag, ##__VA_ARGS__)\n")
            f.write("#endif\n\n")
            
            f.write("#ifndef ESP_LOGD\n")
            f.write("#define ESP_LOGD(tag, format, ...) printf(\"[%s] \" format \"\\n\", tag, ##__VA_ARGS__)\n")
            f.write("#endif\n\n")
            
            f.write("#ifndef ESP_LOGW\n")
            f.write("#define ESP_LOGW(tag, format, ...) printf(\"[%s] WARN: \" format \"\\n\", tag, ##__VA_ARGS__)\n")
            f.write("#endif\n\n")
            
            f.write("#ifndef ESP_LOGE\n")
            f.write("#define ESP_LOGE(tag, format, ...) printf(\"[%s] ERROR: \" format \"\\n\", tag, ##__VA_ARGS__)\n")
            f.write("#endif\n\n")
            
            # Error codes
            f.write("// Error codes\n")
            f.write("#define ESP_OK 0\n")
            f.write("#define ESP_FAIL -1\n")
            f.write("#define ESP_ERR_NO_MEM 0x101\n")
            f.write("#define ESP_ERR_INVALID_ARG 0x102\n")
            f.write("#define ESP_ERR_INVALID_STATE 0x103\n")
            f.write("#define ESP_ERR_INVALID_SIZE 0x104\n")
            f.write("#define ESP_ERR_NOT_FOUND 0x105\n")
            f.write("#define ESP_ERR_NOT_SUPPORTED 0x106\n")
            f.write("#define ESP_ERR_TIMEOUT 0x107\n\n")
            
            f.write("#endif // SDKCONFIG_H\n")
    
    def generate_defaults_file(self, output_file):
        """Generate default configuration file"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# Default Configuration for LaminPie\n")
            f.write("# Generated by config_generator.py\n\n")
            
            for config_name, config_info in self.parser.configs.items():
                if config_info['default'] is not None:
                    if config_info['type'] == 'bool':
                        value = 'y' if config_info['default'] else 'n'
                    elif config_info['type'] == 'int':
                        value = str(config_info['default'])
                    elif config_info['type'] == 'string':
                        value = f'"{config_info["default"]}"'
                    else:
                        value = str(config_info['default'])
                    
                    f.write(f"{config_name}={value}\n")

def main():
    parser = argparse.ArgumentParser(description='Configuration Generator for LaminPie')
    parser.add_argument('kconfig_file', help='Path to main Kconfig file')
    parser.add_argument('-o', '--output', default='sdkconfig.h', help='Output sdkconfig.h file')
    parser.add_argument('-d', '--defaults', help='Default configuration file')
    parser.add_argument('--generate-defaults', help='Generate default configuration file')
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose output')
    
    args = parser.parse_args()
    
    # Create generator instance
    generator = ConfigGenerator()
    
    # Parse Kconfig file
    if not generator.parser.parse_file(args.kconfig_file):
        print(f"Error: Failed to parse Kconfig file: {args.kconfig_file}")
        sys.exit(1)
    
    # Load default configurations if provided
    if args.defaults:
        if not generator.load_defaults(args.defaults):
            print(f"Warning: Could not load defaults file: {args.defaults}")
    
    # Generate sdkconfig.h
    generator.generate_sdkconfig(args.output)
    print(f"Generated sdkconfig.h: {args.output}")
    
    # Generate defaults file if requested
    if args.generate_defaults:
        generator.generate_defaults_file(args.generate_defaults)
        print(f"Generated defaults file: {args.generate_defaults}")
    
    if args.verbose:
        generator.parser.print_summary()

if __name__ == '__main__':
    main()
