#!/usr/bin/env python3
"""
Menuconfig wrapper for LaminPie
Provides a user-friendly interface for configuring LaminPie using menuconfig.
"""

import os
import sys
import argparse
import subprocess
import tempfile
from pathlib import Path

class MenuconfigWrapper:
    def __init__(self, kconfig_file, defaults_file=None):
        self.kconfig_file = kconfig_file
        self.defaults_file = defaults_file
        self.config_file = None
        
    def run_menuconfig(self):
        """Run menuconfig interface"""
        # Check if menuconfig is available
        try:
            result = subprocess.run(['menuconfig', '--help'], 
                                  capture_output=True, text=True, timeout=5)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            print("Error: menuconfig not found. Please install kconfig-frontends.")
            print("On Ubuntu/Debian: sudo apt-get install kconfig-frontends")
            return False
        
        # Create temporary config file if defaults exist
        if self.defaults_file and os.path.exists(self.defaults_file):
            self.config_file = self._create_temp_config()
        
        # Run menuconfig
        cmd = ['menuconfig', self.kconfig_file]
        if self.config_file:
            cmd.extend(['--config', self.config_file])
        
        try:
            result = subprocess.run(cmd)
            return result.returncode == 0
        except KeyboardInterrupt:
            print("\nMenuconfig interrupted by user")
            return False
    
    def _create_temp_config(self):
        """Create temporary config file from defaults"""
        temp_file = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.config')
        
        with open(self.defaults_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    temp_file.write(line + '\n')
        
        temp_file.close()
        return temp_file.name
    
    def save_config(self, output_file):
        """Save current configuration to file"""
        if not self.config_file:
            print("No configuration to save")
            return False
        
        try:
            with open(self.config_file, 'r') as src:
                with open(output_file, 'w') as dst:
                    dst.write("# LaminPie Configuration\n")
                    dst.write("# Generated by menuconfig\n\n")
                    dst.write(src.read())
            return True
        except Exception as e:
            print(f"Error saving config: {e}")
            return False
    
    def cleanup(self):
        """Cleanup temporary files"""
        if self.config_file and os.path.exists(self.config_file):
            os.unlink(self.config_file)

def main():
    parser = argparse.ArgumentParser(description='Menuconfig wrapper for LaminPie')
    parser.add_argument('kconfig_file', help='Path to main Kconfig file')
    parser.add_argument('-d', '--defaults', help='Default configuration file')
    parser.add_argument('-o', '--output', help='Output configuration file')
    parser.add_argument('--no-menuconfig', action='store_true', 
                       help='Skip menuconfig, just process defaults')
    
    args = parser.parse_args()
    
    # Create wrapper instance
    wrapper = MenuconfigWrapper(args.kconfig_file, args.defaults)
    
    try:
        if not args.no_menuconfig:
            print("Starting menuconfig...")
            print("Use arrow keys to navigate, Enter to select, Esc to go back")
            print("Press '?' for help on any option")
            print("Press 'q' to quit and save")
            
            if not wrapper.run_menuconfig():
                print("Menuconfig failed or was cancelled")
                return 1
        
        # Save configuration if output specified
        if args.output:
            if wrapper.save_config(args.output):
                print(f"Configuration saved to: {args.output}")
            else:
                print("Failed to save configuration")
                return 1
        
        return 0
        
    finally:
        wrapper.cleanup()

if __name__ == '__main__':
    sys.exit(main())
