/*
 * SDK Configuration Header for LaminPie
 * Auto-generated from Kconfig files
 * Generated by config_generator.py
 */

#ifndef SDKCONFIG_H
#define SDKCONFIG_H

// ============================================================================
// Platform Configuration
// ============================================================================

#define CONFIG_PLATFORM_GENERIC 1

// ============================================================================
// LaminPie Core Configuration
// ============================================================================

#define CONFIG_LAMINPIE_GUI_ENABLE_ANIM_PLAYER 0
#define CONFIG_LAMINPIE_GUI_ENABLE_SQUARELINE 0
#define CONFIG_LAMINPIE_SERVICES_ENABLE_STORAGE 1

// ============================================================================
// Platform-Specific Definitions
// ============================================================================

#ifndef __cplusplus
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#endif

#ifndef ARRAY_SIZE
#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
#endif

#ifndef MIN
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#endif

#ifndef MAX
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#endif

// ESP-IDF compatibility macros
#ifndef ESP_LOGI
#define ESP_LOGI(tag, format, ...) printf("[%s] " format "\n", tag, ##__VA_ARGS__)
#endif

#ifndef ESP_LOGD
#define ESP_LOGD(tag, format, ...) printf("[%s] " format "\n", tag, ##__VA_ARGS__)
#endif

#ifndef ESP_LOGW
#define ESP_LOGW(tag, format, ...) printf("[%s] WARN: " format "\n", tag, ##__VA_ARGS__)
#endif

#ifndef ESP_LOGE
#define ESP_LOGE(tag, format, ...) printf("[%s] ERROR: " format "\n", tag, ##__VA_ARGS__)
#endif

// Error codes
#define ESP_OK 0
#define ESP_FAIL -1
#define ESP_ERR_NO_MEM 0x101
#define ESP_ERR_INVALID_ARG 0x102
#define ESP_ERR_INVALID_STATE 0x103
#define ESP_ERR_INVALID_SIZE 0x104
#define ESP_ERR_NOT_FOUND 0x105
#define ESP_ERR_NOT_SUPPORTED 0x106
#define ESP_ERR_TIMEOUT 0x107

#endif // SDKCONFIG_H
