#ifndef LAMINPIE_TEST_CONFIG_H
#define LAMINPIE_TEST_CONFIG_H

// 测试配置选项
#define ENABLE_UNIT_TESTS true
#define ENABLE_INTEGRATION_TESTS true
#define ENABLE_PERFORMANCE_TESTS true
#define ENABLE_STRESS_TESTS true

// 测试超时配置
#define UNIT_TEST_TIMEOUT_MS 1000
#define INTEGRATION_TEST_TIMEOUT_MS 5000
#define PERFORMANCE_TEST_TIMEOUT_MS 10000
#define STRESS_TEST_TIMEOUT_MS 30000

// 性能测试配置
#define PERFORMANCE_TEST_ITERATIONS 100
#define STRESS_TEST_ITERATIONS 1000
#define MEMORY_TEST_ITERATIONS 100

// 日志配置
#define TEST_LOG_LEVEL_DEBUG true
#define TEST_LOG_LEVEL_INFO true
#define TEST_LOG_LEVEL_WARN true
#define TEST_LOG_LEVEL_ERROR true

#endif // LAMINPIE_TEST_CONFIG_H